jobs:
  ci:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build with Maven
      run: mvn --batch-mode --no-transfer-progress verify --define skipTests=true
    strategy:
      matrix:
        java:
        - 11
        - 17
        - 21
        - 22-ea
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
name: CI
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
permissions:
  contents: read
